[package]
name = "hello"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws_lambda_events = "0.12.1"
http = "1.0.0"
lambda_runtime = "0.8.3"
log = "0.4.14"
simple_logger = "4.3.0"
tokio = "1.6.1"